#!/bin/bash

# Example:
#
# CREATE DATABASE mypets
# CREATE TABLE dogs (name VARCHAR PRIMARY KEY, breed VARCHAR);
# CREATE FUNCTION about(dogs) RETURNS text LANGUAGE SQL AS $$
#   SELECT $1.name || ' is a ' || $1.breed;
# $$
#
# mypets dogs new --name=Pluto --breed=bloodhound
# mypets dogs new --name=Spike --breed=bulldog
# mypets dogs show
# mypets dogs new --name=Pongo --breed=dalmatian
# mypets dogs show --name=Spike
# mypets dogs new --name='Santa'\''s Little Helper' --breed=greyhound
# mypets dogs show
# mypets dogs new --name=Ren --breed=Stimpy
# mypets dogs show
# mypets dogs set --breed=chihuahua on --name=Ren
# mypets dogs show
# mypets dogs delete --name=Spike
# mypets dogs show
# mypets dogs about --name=Ren

DBNAME=$(basename $0)
DBTABLE=$1
COMMAND=$2

SET=0
[ "$COMMAND" = "set" ] && SET=1

shift
shift

while [ ! -z "$1" ]; do
    argcore=${1#--}
    if [ "$1" = "on" ]; then
        SET=0
        shift
        continue
    fi
    if [ "$1" = "$argcore" ]; then
        echo "$DBNAME: unrecognized keyword: $1"
        exit 2
    fi
    fieldname=${argcore%=*}
    value=${argcore#*=}
    if [ "$SET" -eq "1" ]; then
        updates+=("$fieldname = \$\$$value\$\$")
    else
        conditions+=("$fieldname = \$\$$value\$\$")
    fi
    fields+=("$fieldname")
    values+=("\$\$$value\$\$")
    shift
done

setlist=$(printf -v var "%s, " "${updates[@]}"; echo "${var%, }")
fieldlist=$(printf -v var "%s, " "${fields[@]}"; echo "${var%, }")
valuelist=$(printf -v var "%s, " "${values[@]}"; echo "${var%, }")
whereclause=$(echo -n "WHERE ("; printf -v var "%s) AND (" "${conditions[@]}"; echo "${var% AND (}")
[ "$whereclause" = "WHERE ()" ] && unset whereclause

if [ "$COMMAND" == "show" ]; then
    SQL="SELECT * FROM $DBTABLE $whereclause;"
elif [ "$COMMAND" == "new" ]; then
    SQL="INSERT INTO $DBTABLE ($fieldlist) VALUES ($valuelist);"
elif [ "$COMMAND" == "set" ]; then
    SQL="UPDATE $DBTABLE SET $setlist $whereclause"
elif [ "$COMMAND" == "delete" ]; then
    SQL="DELETE FROM $DBTABLE $whereclause;"
else
    SQL="SELECT $DBTABLE.$COMMAND FROM $DBTABLE $whereclause;"
fi

psql -c "$SQL" "$DBNAME"
